# Generated by Django 2.0.13 on 2020-02-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField()),
                ('complete', models.BooleanField()),
            ],
        ),
    ]
